name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package:
    permissions:
      contents: read
      pull-requests: read
    uses: global-torque/.github/.github/workflows/public-package-ci.yml@e858506acc0ee9ec8146266355f12232242cd6c8
